apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-container
        image: ghcr.io/slvdemo/app:latest
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
        ports:
        - containerPort: 8888
      serviceAccountName: app-account
