---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-account
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - "get"
      - "list"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
subjects:
- kind: ServiceAccount
  name: app-account
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io
