---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-account
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:
      - "get"
      - "list"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
subjects:
- kind: ServiceAccount
  name: app-account
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-container
        image: ghcr.io/slvdemo/app:latest
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
        ports:
        - containerPort: 8888
      serviceAccountName: app-account

---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 32123
  selector:
    app: app
