name: Deploy

on:
  workflow_dispatch:

jobs:
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Load Secrets using SLV
          uses: amagioss/slv-action@main
          with:
            vault: deploy/prod.slv.yaml
            env-secret-key: ${{ secrets.SLV_ENV_SECRET_KEY }}
            prefix: "APP_DEPLOY_"
        - name: copy file via ssh key
          uses: appleboy/scp-action@v0.1.7
          with:
            host: ${{ env.APP_DEPLOY_HOST }}
            username: ${{ env.APP_DEPLOY_USER }}
            key: ${{ env.APP_DEPLOY_SSH_PRIVATE_KEY }}
            source: "deploy"
            target: "~/"
        - name: Deploy SLV Operator and App
          uses: appleboy/ssh-action@v1.0.3
          env:
            SLV_ENV_SECRET_KEY: ${{ secrets.SLV_ENV_SECRET_KEY }}
          with:
            host: ${{ env.APP_DEPLOY_HOST }}
            username: ${{ env.APP_DEPLOY_USER }}
            key: ${{ env.APP_DEPLOY_SSH_PRIVATE_KEY }}
            envs: SLV_ENV_SECRET_KEY
            script: |
                echo "Deploying the SLV Operator and App"
                slv vault deref -v deploy/prod.slv.yaml --path deploy/slv.yaml
                kubectl apply -f deploy/app.yaml
                kubectl apply -f kubectl apply -f https://oss.amagi.com/slv/k8s/crd.yaml
                kubectl apply -f deploy/slv-operator.yaml
                rm -rf deploy
